/*
 * Recipebase REST API
 * Recipe database API description.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package hu.bme.aut.recipebase.model.network

import com.google.gson.annotations.SerializedName
import io.swagger.annotations.ApiModelProperty
import java.lang.StringBuilder
import java.util.*

/**
 * Credit
 */
class Credit {
    /**
     * Get name
     * @return name
     */
    @get:ApiModelProperty(example = "Alexandra Covello", value = "")
    @SerializedName("name")
    var name: String? = null

    /**
     * Get type
     * @return type
     */
    @get:ApiModelProperty(example = "internal", value = "")
    @SerializedName("type")
    var type: String? = null
    fun name(name: String?): Credit {
        this.name = name
        return this
    }

    fun type(type: String?): Credit {
        this.type = type
        return this
    }

    override fun equals(o: Any?): Boolean {
        if (this === o) {
            return true
        }
        if (o == null || javaClass != o.javaClass) {
            return false
        }
        val credit = o as Credit
        return name == credit.name &&
                type == credit.type
    }

    override fun hashCode(): Int {
        return Objects.hash(name, type)
    }

    override fun toString(): String {
        val sb = StringBuilder()
        sb.append("class Credit {\n")
        sb.append("    name: ").append(toIndentedString(name)).append("\n")
        sb.append("    type: ").append(toIndentedString(type)).append("\n")
        sb.append("}")
        return sb.toString()
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private fun toIndentedString(o: Any?): String {
        return o?.toString()?.replace("\n", "\n    ") ?: "null"
    }
}