/*
 * Recipebase REST API
 * Recipe database API description.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package hu.bme.aut.recipebase.model.network

import com.google.gson.annotations.SerializedName
import io.swagger.annotations.ApiModelProperty
import java.lang.StringBuilder
import java.util.*

/**
 * Unit
 */
class Unit {
    /**
     * Get system
     * @return system
     */
    @get:ApiModelProperty(example = "none", value = "")
    @SerializedName("system")
    var system: String? = null

    /**
     * Get name
     * @return name
     */
    @get:ApiModelProperty(value = "")
    @SerializedName("name")
    var name: String? = null

    /**
     * Get displayPlural
     * @return displayPlural
     */
    @get:ApiModelProperty(value = "")
    @SerializedName("display_plural")
    var displayPlural: String? = null

    /**
     * Get displaySingular
     * @return displaySingular
     */
    @get:ApiModelProperty(value = "")
    @SerializedName("display_singular")
    var displaySingular: String? = null

    /**
     * Get abbreviation
     * @return abbreviation
     */
    @get:ApiModelProperty(value = "")
    @SerializedName("abbreviation")
    var abbreviation: String? = null
    fun system(system: String?): Unit {
        this.system = system
        return this
    }

    fun name(name: String?): Unit {
        this.name = name
        return this
    }

    fun displayPlural(displayPlural: String?): Unit {
        this.displayPlural = displayPlural
        return this
    }

    fun displaySingular(displaySingular: String?): Unit {
        this.displaySingular = displaySingular
        return this
    }

    fun abbreviation(abbreviation: String?): Unit {
        this.abbreviation = abbreviation
        return this
    }

    override fun equals(o: Any?): Boolean {
        if (this === o) {
            return true
        }
        if (o == null || javaClass != o.javaClass) {
            return false
        }
        val unit = o as Unit
        return system == unit.system &&
                name == unit.name &&
                displayPlural == unit.displayPlural &&
                displaySingular == unit.displaySingular &&
                abbreviation == unit.abbreviation
    }

    override fun hashCode(): Int {
        return Objects.hash(system, name, displayPlural, displaySingular, abbreviation)
    }

    override fun toString(): String {
        val sb = StringBuilder()
        sb.append("class Unit {\n")
        sb.append("    system: ").append(toIndentedString(system)).append("\n")
        sb.append("    name: ").append(toIndentedString(name)).append("\n")
        sb.append("    displayPlural: ").append(toIndentedString(displayPlural)).append("\n")
        sb.append("    displaySingular: ").append(toIndentedString(displaySingular)).append("\n")
        sb.append("    abbreviation: ").append(toIndentedString(abbreviation)).append("\n")
        sb.append("}")
        return sb.toString()
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private fun toIndentedString(o: Any?): String {
        return o?.toString()?.replace("\n", "\n    ") ?: "null"
    }
}